import Head from "next/head";
import Feed from "../components/Feed/Feed";
import Sidebar from "../components/Sidebar/Sidebar";
import Widget from "../components/Widget/Widget";

export default function Home({ newsResults }) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-[90rem] mx-auto">
        {/* sidebar */}
        <Sidebar />

        {/* feed */}
        <Feed />
        {/* widgets */}
        <Widget newsResults={newsResults.articles} />
        {/* modal */}
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/technology/in.json

export async function getServerSideProps() {
  const newsResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/technology/in.json')
    .then(res => res.json())
  return {
    props: {
      newsResults,
    }
  }

}